# Generated by Django 5.2.5 on 2025-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='מספר פלאפון')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='קישור לפייסבוק')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='קישור לוואטסאפ')),
            ],
            options={
                'verbose_name': 'פרטי יצירת קשר',
                'verbose_name_plural': 'פרטי יצירת קשר',
            },
        ),
    ]
