# Generated by Django 5.2.5 on 2025-08-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_contentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="CSS class (למשל: 'fa fa-star') או קישור לתמונה", max_length=255)),
                ('icon_type', models.CharField(choices=[('class', 'CSS Class'), ('url', 'Image URL')], default='class', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='סדר הופעה ברשימה')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
