# Generated by Django 5.2.5 on 2025-08-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_featuregrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuregrid',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
