# Generated by Django 5.2.5 on 2025-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0006_featuregrid_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='hero/videos/')),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
