# Generated by Django 5.2.5 on 2025-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0007_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=20, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='split_sections/')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='split_sections/')),
            ],
        ),
    ]
