# Generated by Django 5.2.5 on 2025-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0008_splitsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsection',
            name='text_color',
            field=models.CharField(blank=True, default='#000000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='splitsection',
            name='background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=20, null=True),
        ),
    ]
