# Generated by Django 5.2.5 on 2025-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0009_splitsection_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsection',
            name='text_color_title',
            field=models.CharField(blank=True, default='#000000', max_length=20, null=True),
        ),
    ]
